[package]
edition      = "2024"
name         = "asg-device"
rust-version = "1.95"
version      = "0.1.0"

[[bin]]
name = "asg-device"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.2.2", features = ["esp32s3", "log-04", "unstable"] }

esp-rtos = { version = "0.4.0", features = ["embassy", "esp32s3", "log-04"] }

esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3", "log-04"] }
log                    = "0.4.27"

embassy-executor = { version = "0.10.0", features = ["log"] }
embassy-time = { version = "0.5.0", features = ["log"] }
esp-backtrace = { version = "0.20.0", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.18.0", features = ["esp32s3", "log-04"] }

static_cell      = "2.1.1"

asg-core = { path = "../core" }

[features]
default = ["v4-r2"]
v4-r2   = [] # Heltec V4 R2: 2 MB PSRAM
v4-r8   = [] # Heltec V4 R8: 8 MB octal PSRAM


# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
